// Code generated by tmpltype; DO NOT EDIT.
package main

var basic_typesTplSource = `{{- /* @param Name string */ -}}
{{- /* @param Age int */ -}}
{{- /* @param Score int64 */ -}}
{{- /* @param Price float64 */ -}}
{{- /* @param Active bool */ -}}
=== Basic Types ===

Name: {{ .Name }}
Age: {{ .Age }}
Score: {{ .Score }}
Price: ${{ .Price }}
Active: {{ .Active }}
`

var complex_typesTplSource = `{{- /* @param Items []struct{ID int64; Title string; Tags []string; Price float64} */ -}}
{{- /* @param OptionalItems *[]string */ -}}
{{- /* @param Records []struct{Name string; Age int; Score *int} */ -}}
=== Complex/Nested Types ===

## Items (slice of structs):
{{- range .Items }}
- ID: {{ .ID }}, Title: {{ .Title }}, Price: ${{ .Price }}
  Tags: {{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag }}{{ end }}
{{- end }}

## Optional Items:
{{- if .OptionalItems }}
{{- range .OptionalItems }}
- {{ . }}
{{- end }}
{{- else }}
(not provided)
{{- end }}

## Records (slice of structs with optional fields):
{{- range .Records }}
- Name: {{ .Name }}, Age: {{ .Age }}
  Score: {{ if .Score }}{{ .Score }}{{ else }}(not set){{ end }}
{{- end }}
`

var map_typesTplSource = `{{- /* @param Metadata map[string]string */ -}}
{{- /* @param Counters map[string]int */ -}}
{{- /* @param Prices map[string]float64 */ -}}
{{- /* @param Features map[string]bool */ -}}
=== Map Types ===

Metadata:
{{- range $key, $value := .Metadata }}
  - {{ $key }}: {{ $value }}
{{- end }}
Counters:
{{- range $key, $value := .Counters }}
  - {{ $key }}: {{ $value }}
{{- end }}
Prices:
{{- range $key, $value := .Prices }}
  - {{ $key }}: ${{ $value }}
{{- end }}
Features:
{{- range $key, $value := .Features }}
  - {{ $key }}: {{ $value }}
{{- end }}
`

var pointer_typesTplSource = `{{- /* @param Email *string */ -}}
{{- /* @param PhoneNumber *string */ -}}
{{- /* @param MiddleScore *int */ -}}
{{- /* @param Discount *float64 */ -}}
=== Pointer Types (Optional Fields) ===

{{- if .Email }}
Email: {{ .Email }}
{{- else }}
Email: (not provided)
{{- end }}
{{- if .PhoneNumber }}
Phone: {{ .PhoneNumber }}
{{- else }}
Phone: (not provided)
{{- end }}
{{- if .MiddleScore }}
Middle Score: {{ .MiddleScore }}
{{- else }}
Middle Score: (not provided)
{{- end }}
{{- if .Discount }}
Discount: {{ .Discount }}%
{{- else }}
Discount: (not provided)
{{- end }}
`

var slice_typesTplSource = `{{- /* @param Tags []string */ -}}
{{- /* @param CategoryIDs []int */ -}}
{{- /* @param Ratings []float64 */ -}}
{{- /* @param Flags []bool */ -}}
=== Slice Types ===

Tags: {{ range $i, $tag := .Tags }}{{ if $i }}, {{ end }}{{ $tag }}{{ end }}
Category IDs: {{ range $i, $id := .CategoryIDs }}{{ if $i }}, {{ end }}{{ $id }}{{ end }}
Ratings: {{ range $i, $rating := .Ratings }}{{ if $i }}, {{ end }}{{ $rating }}{{ end }}
Flags: {{ range $i, $flag := .Flags }}{{ if $i }}, {{ end }}{{ $flag }}{{ end }}
`

var struct_typesTplSource = `{{- /* @param User.ID int64 */ -}}
{{- /* @param User.Name string */ -}}
{{- /* @param User.Email string */ -}}
{{- /* @param Product.SKU string */ -}}
{{- /* @param Product.Price float64 */ -}}
{{- /* @param Product.InStock bool */ -}}
=== Struct Types (Nested Fields) ===

User: ID={{ .User.ID }}, Name={{ .User.Name }}, Email={{ .User.Email }}
Product: SKU={{ .Product.SKU }}, Price=${{ .Product.Price }}, InStock={{ .Product.InStock }}
`
