// Code generated by tmpltype; DO NOT EDIT.
package main

var footerTplSource = `{{- /* @param Year int */ -}}
{{- /* @param CompanyName string */ -}}
{{- /* @param Links []struct{Text string; URL string} */ -}}
    <footer>
        <div class="links">
            {{ range .Links }}
            <a href="{{ .URL }}">{{ .Text }}</a>
            {{ end }}
        </div>
        <p>&copy; {{ .Year }} {{ .CompanyName }}. All rights reserved.</p>
    </footer>
</body>
</html>`

var headerTplSource = `{{- /* @param Title string */ -}}
{{- /* @param Subtitle *string */ -}}
<!DOCTYPE html>
<html>
<head>
    <title>{{ .Title }}</title>
</head>
<body>
    <header>
        <h1>{{ .Title }}</h1>
        {{ if .Subtitle }}<h2>{{ .Subtitle }}</h2>{{ end }}
    </header>`

var navTplSource = `{{- /* @param Items []struct{Name string; Link string; Active bool} */ -}}
{{- /* @param CurrentUser.Name string */ -}}
{{- /* @param CurrentUser.IsAdmin bool */ -}}
<nav>
    <ul>
    {{ range .Items }}
        <li{{ if .Active }} class="active"{{ end }}>
            <a href="{{ .Link }}">{{ .Name }}</a>
        </li>
    {{ end }}
    </ul>
    <div class="user-info">
        Logged in as: {{ .CurrentUser.Name }}
        {{ if .CurrentUser.IsAdmin }}(Admin){{ end }}
    </div>
</nav>`
