// Code generated by tmpltype; DO NOT EDIT.
package main

import (
	"fmt"
	"io"
	"sync"
	"text/template"
)

// TemplateName is a type-safe template name
type TemplateName string

// Template provides type-safe access to template names
var Template = struct {
	メール TemplateName
}{
	メール: "メール",
}

// TemplateOption configures template initialization
type TemplateOption func(*templateConfig)

type templateConfig struct {
	funcs template.FuncMap
}

// WithFuncs sets custom template functions
func WithFuncs(funcs template.FuncMap) TemplateOption {
	return func(c *templateConfig) {
		c.funcs = funcs
	}
}

var templates map[TemplateName]*template.Template
var initOnce sync.Once

// InitTemplates initializes all templates with the given options.
// Must be called before using any render functions.
//
// Example:
//
//	InitTemplates() // without custom functions
//	InitTemplates(WithFuncs(GetTemplateFuncs())) // with custom functions
func InitTemplates(opts ...TemplateOption) {
	initOnce.Do(func() {
		config := &templateConfig{}
		for _, opt := range opts {
			opt(config)
		}

		templates = map[TemplateName]*template.Template{
			Template.メール: newTemplate(Template.メール, メールTplSource, config),
		}
	})
}

func newTemplate(name TemplateName, source string, config *templateConfig) *template.Template {
	t := template.New(string(name))
	if config.funcs != nil {
		t = t.Funcs(config.funcs)
	}
	return template.Must(t.Option("missingkey=error").Parse(source))
}

// Templates returns a map of all templates
func Templates() map[TemplateName]*template.Template {
	return templates
}

// Render renders a template by name with the given data
func Render(w io.Writer, name TemplateName, data any) error {
	if templates == nil {
		return fmt.Errorf("templates not initialized: call InitTemplates() first")
	}
	tmpl, ok := templates[name]
	if !ok {
		return fmt.Errorf("template %q not found", name)
	}
	return tmpl.Execute(w, data)
}

// ============================================================
// メール template
// ============================================================

// メール represents parameters for メール template
type メール struct {
	Name string
}

// Renderメール renders the メール template
func Renderメール(w io.Writer, p メール) error {
	if templates == nil {
		return fmt.Errorf("templates not initialized: call InitTemplates() first")
	}
	tmpl, ok := templates[Template.メール]
	if !ok {
		return fmt.Errorf("template %q not found", Template.メール)
	}
	return tmpl.Execute(w, p)
}
