// Code generated by tmpltype; DO NOT EDIT.
package main

var emailTplSource = `{{/* @param CreatedAt time.Time */}}
{{/* @param Price int */}}
<!DOCTYPE html>
<html>
<head>
    <title>{{ .Title | upper }}</title>
</head>
<body>
    <h1>Hello, {{ .User.Name | upper }}!</h1>
    <p>Email: {{ .User.Email | lower }}</p>

    <p>Created: {{ formatDate .CreatedAt }}</p>
    <p>Last updated: {{ formatDateTime .CreatedAt }}</p>

    <div class="message">
        {{ nl2br .Message }}
    </div>

    <p>Price: ${{ comma .Price }}</p>

    <p>URL: {{ default "https://example.com" .URL }}</p>

    {{/* Example of custom function not in preset */}}
    <p>Custom: {{ myCustomFunction .Title }}</p>
</body>
</html>
`
