// Code generated by tmpltype; DO NOT EDIT.
package main

var advancedTplSource = `<!DOCTYPE html>
<html>
<head>
    <title>Advanced - Template Features</title>
</head>
<body>
    <h1>Advanced Template Patterns</h1>

    {{/* 7. Nested structures: with + range */}}
    <section id="nested-structures">
        <h2>Nested Structures (With + Range)</h2>
        {{ with .Project }}
        <div class="project-details">
            <h3>{{ .Name }}</h3>
            <p>{{ .Description }}</p>
            {{ range .Tasks }}
            <article class="task">
                <h4>{{ .Title }}</h4>
                <p>Status: {{ .Status }}</p>
            </article>
            {{ end }}
        </div>
        {{ end }}
    </section>

    {{/* 8. Deep nested path */}}
    <section id="deep-nested">
        <h2>Deep Nested Path</h2>
        <p>Organization: {{ .Company.Department.Team.Manager.Name }}</p>
    </section>

    <footer>
        <p>Generated by tmpltype - Advanced Template</p>
    </footer>
</body>
</html>
`

var basic_fieldsTplSource = `<!DOCTYPE html>
<html>
<head>
    <title>Basic Fields - Template Features</title>
</head>
<body>
    <h1>Basic Field Reference</h1>

    {{/* 1. Basic field reference */}}
    <section id="basic">
        <h2>Basic Field Reference</h2>
        <p>Title: {{ .Title }}</p>
    </section>

    {{/* 2. Nested field reference */}}
    <section id="nested">
        <h2>Nested Field Reference</h2>
        <p>Author: {{ .Author.Name }}</p>
        <p>Email: {{ .Author.Email }}</p>
    </section>

    <footer>
        <p>Generated by tmpltype - Basic Fields Template</p>
    </footer>
</body>
</html>
`

var collectionsTplSource = `<!DOCTYPE html>
<html>
<head>
    <title>Collections - Template Features</title>
</head>
<body>
    <h1>Working with Collections</h1>

    {{/* 5. Range over slice */}}
    <section id="range">
        <h2>Range Over Slice</h2>
        <ul class="items">
        {{ range .Items }}
            <li>
                <strong>{{ .Title }}</strong>
                <span>ID: {{ .ID }}</span>
                <p>{{ .Description }}</p>
            </li>
        {{ end }}
        </ul>
    </section>

    {{/* 6. Index function for map access */}}
    <section id="map">
        <h2>Map Access with Index Function</h2>
        <dl class="metadata">
            <dt>Environment</dt>
            <dd>{{ index .Meta "env" }}</dd>
            <dt>Version</dt>
            <dd>{{ index .Meta "version" }}</dd>
            <dt>Build</dt>
            <dd>{{ index .Meta "build" }}</dd>
        </dl>
    </section>

    <footer>
        <p>Generated by tmpltype - Collections Template</p>
    </footer>
</body>
</html>
`

var control_flowTplSource = `<!DOCTYPE html>
<html>
<head>
    <title>Control Flow - Template Features</title>
</head>
<body>
    <h1>Control Flow Statements</h1>

    {{/* 3. If statement */}}
    <section id="conditional">
        <h2>Conditional Rendering</h2>
        {{ if .Status }}
        <p class="status">Status: {{ .Status }}</p>
        {{ end }}
    </section>

    {{/* 4. With statement and else clause */}}
    <section id="with-else">
        <h2>With Statement and Else Clause</h2>
        {{ with .Summary }}
        <div class="summary">
            <h3>Summary</h3>
            <p>{{ .Content }}</p>
            <p>Updated: {{ .LastUpdated }}</p>
        </div>
        {{ else }}
        <p>No summary available. Default message: {{ .DefaultMessage }}</p>
        {{ end }}
    </section>

    <footer>
        <p>Generated by tmpltype - Control Flow Template</p>
    </footer>
</body>
</html>
`
