// Code generated by tmpltype; DO NOT EDIT.
package main

import (
	"fmt"
	"io"
	"text/template"
)

// TemplateName is a type-safe template name
type TemplateName string

// Template provides type-safe access to template names
var Template = struct {
	Email TemplateName
}{
	Email: "email",
}

func newTemplate(name TemplateName, source string) *template.Template {
	return template.Must(template.New(string(name)).Option("missingkey=error").Parse(source))
}

var templates = map[TemplateName]*template.Template{
	Template.Email: newTemplate(Template.Email, emailTplSource),
}

// Templates returns a map of all templates
func Templates() map[TemplateName]*template.Template {
	return templates
}

// Render renders a template by name with the given data
func Render(w io.Writer, name TemplateName, data any) error {
	tmpl, ok := templates[name]
	if !ok {
		return fmt.Errorf("template %q not found", name)
	}
	return tmpl.Execute(w, data)
}

// ============================================================
// email template
// ============================================================

type EmailUser struct {
	Name string
}

// Email represents parameters for email template
type Email struct {
	Message string
	User    EmailUser
}

// RenderEmail renders the email template
func RenderEmail(w io.Writer, p Email) error {
	tmpl, ok := templates[Template.Email]
	if !ok {
		return fmt.Errorf("template %q not found", Template.Email)
	}
	return tmpl.Execute(w, p)
}
