// Code generated by tmpltype; DO NOT EDIT.
package main

var footerTplSource = `---
{{ .SiteName }} | {{ .Year }}
Contact: {{ .Email }}
---`

var mail_account_created_contentTplSource = `Hello {{ .Username }},

Your account has been successfully created!

Username: {{ .Username }}
Email: {{ .Email }}

You can now log in and start using {{ .SiteName }}.

Best regards,
The {{ .SiteName }} Team`

var mail_account_created_titleTplSource = `Welcome to {{ .SiteName }}!`

var mail_article_created_contentTplSource = `Hello,

A new article has been published on {{ .SiteName }}:

Title: {{ .ArticleTitle }}
Author: {{ .AuthorName }}
URL: {{ .ArticleURL }}

Excerpt:
{{ .Excerpt }}

Check it out now!

Best regards,
The {{ .SiteName }} Team`

var mail_article_created_titleTplSource = `New article published: {{ .ArticleTitle }}`

var mail_invite_contentTplSource = `Hello {{ .RecipientName }},

{{ .InviterName }} has invited you to join {{ .SiteName }}.

Please click the link below to accept the invitation:
{{ .InviteURL }}

Best regards,
The {{ .SiteName }} Team`

var mail_invite_titleTplSource = `{{ .SiteName }}: Invitation from {{ .InviterName }}`
